# Generated by Django 5.1.3 on 2024-12-11 20:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('media', '0001_initial'), ('media', '0002_remove_movie_director_movie_directors'), ('media', '0003_rename_genre_movie_genres_and_more'), ('media', '0004_movie_approved_videogame_approved'), ('media', '0005_alter_movie_options_alter_videogame_options'), ('media', '0006_alter_movie_options_alter_videogame_options'), ('media', '0007_alter_movie_options_alter_videogame_options'), ('media', '0008_movie_date_added_videogame_date_added'), ('media', '0009_alter_movie_options_alter_videogame_options'), ('media', '0010_alter_movie_poster_alter_videogame_poster')]

    initial = True

    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoGameGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('poster', models.ImageField(upload_to='posters/movies/', verbose_name='Poster')),
                ('genres', models.ManyToManyField(related_name='movies', to='media.moviegenre')),
                ('directors', models.ManyToManyField(related_name='movies', to='creators.director', verbose_name='Directors')),
                ('approved', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
                'permissions': [('can_suggest_movies', 'Can suggest movies'), ('can_approve_movies', 'Can approve movies')],
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='VideoGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('release_date', models.DateField(verbose_name='Release Date')),
                ('poster', models.ImageField(upload_to='posters/games/')),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='creators.developer', verbose_name='Developer')),
                ('genres', models.ManyToManyField(related_name='games', to='media.videogamegenre')),
                ('approved', models.BooleanField(default=False)),
                ('date_added', models.DateField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
                'permissions': [('can_suggest_games', 'Can suggest video games'), ('can_approve_games', 'Can approve video games')],
                'ordering': ['title'],
            },
        ),
    ]
