# Generated by Django 5.1.3 on 2024-11-13 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_remove_movie_director_movie_directors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='videogame',
            old_name='genre',
            new_name='genres',
        ),
    ]
