# Generated by Django 5.1.3 on 2024-12-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_movie_approved_videogame_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'permissions': [('can_approve_media', 'Can approve media')]},
        ),
        migrations.AlterModelOptions(
            name='videogame',
            options={'permissions': [('can_approve_media', 'Can approve media')]},
        ),
    ]
