# Generated by Django 5.1.3 on 2024-12-11 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_movie_date_added_videogame_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['title'], 'permissions': [('can_suggest_movies', 'Can suggest movies'), ('can_approve_movies', 'Can approve movies')]},
        ),
        migrations.AlterModelOptions(
            name='videogame',
            options={'ordering': ['title'], 'permissions': [('can_suggest_games', 'Can suggest video games'), ('can_approve_games', 'Can approve video games')]},
        ),
    ]
