# Generated by Django 5.1.3 on 2024-12-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_alter_movie_options_alter_videogame_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='posters/movies/', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='poster',
            field=models.ImageField(upload_to='posters/games/'),
        ),
    ]
