# Generated by Django 5.1.3 on 2024-12-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_squashed_0010_alter_movie_poster_alter_videogame_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='videogame',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
