# Generated by Django 5.1.3 on 2024-12-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('creators', '0001_initial'), ('creators', '0002_alter_developer_options_alter_director_options')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_name', models.CharField(max_length=255, unique=True, verbose_name='Developer Name')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
            ],
            options={
                'ordering': ['developer_name'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
